ポーリング対象範囲の改善と伴う変数の追加
traP-jp/traQ-gazer pull request #133
Opened 2024-01-24 06:11 UTC by alter334

messagePollar周りの改善案です
goルーチンに対する理解が浅いため,並行処理でちゃんと動くか把握できてないので問題があれば教えてください

## やってみたこと

### メッセージポーリング範囲を~~1分追加~~改善
- SearchMessagesAPIが直近数十秒の投稿を拾うか否か不安定なため(取得もれもここで起きているものがあると考えられる)
- ~~この変更以外が現在の仕様の場合**3分ごとに直近4分の投稿を拾う**仕様になる~~
- メッセージ収集のfromを前回検索時の最新メッセージの投稿日時にした

### messageProcessorにlastCheckMessage(string),tmplastCheckMessage(string)を追加&それに対応した既存メソッドの変更
- 前回のポーリングで取得した最新メッセージのUUIDを格納(lastCheck...)
- 先の仕様変更によりポーリング対象が広くなっているため重複してDM送られる可能性がある
- そのため、前回集計で扱ったメッセージが現れた場合にメッセージ読み取りを終了するようにした(これにより該当メッセージが削除されない限り重複したDMは発生しない...筈)
- tmplast... については並行処理を考慮して設定(そもそも並行処理に対して知識が浅いので上手くいくか分からないです)

2024-01-25 00:51 UTC, Pugma reviewed
パッと見だとこれくらいです

ただUUIDで管理するんじゃなく、前回取得時の最新メッセージの投稿時刻を検索クエリのAfterに入れるっていう案が出ていて、そちらのほうが投稿が削除された場合でも不具合がないのかな、と思っています

2024-01-25 00:57 UTC, alter334 commented on server/traqmessage/collect.go
>  		for {
デフォルト値を0で強調させたかったって感じです
開発規則等でそのように表記するよう整えられてたりしましたら修正します

2024-01-25 01:00 UTC, alter334 commented
最新メッセージの投稿時間を記録しておく方法なら若干ブラックボックス気味な並行処理部分での条件分岐が要らなくなりそうです
試してみます

2024-01-25 01:18 UTC, alter334 commented
元の実装にかなり近くなった気がします goルーチン中での処理が消えました:iihanashi:

2024-01-25 01:25 UTC, Pugma commented on server/traqmessage/collect.go
>  		for {
特に決まってるワケじゃないのでそんな気にしないで
なんで変えたのかなってちょっと気になっただけだよ
確かにこっちのほうがそんなにGolangに詳しくない人でも分かりやすそうね

2024-01-25 01:28 UTC, alter334 commented on server/traqmessage/collect.go
>  		for {
まあ元の実装にできるだけ近づけておきたいという思想があったので元に戻しました
デフォ値がちゃんと0で設定される言語とそうで無いのもあるからなぁ

2024-01-25 01:32 UTC, Pugma requested changes
最新の投稿時刻を保持するにあたって、DBでテーブルを作っておく必要があると思うのでお願いします
現状だと再起動時は最新時刻を起点に収集するはずで、前回の最新投稿の時間を使えないので収集漏れの可能性があります

2024-01-25 01:44 UTC, Pugma commented on server/traqmessage/collect.go
> +			}
このあたりの条件分岐、他に立ってる #131 の変更点と合わせるともう少し簡略化できそうな気がしています
`TotalHits`→`page`の順でチェックするとコードがスッキリするかな:tabun:

2024-01-25 02:20 UTC, Pugma commented on server/traqmessage/collect.go
> +			}
#131 のマージをしたので一部conflictが発生していますが、今の実装をもとにTotalHitsとかを↑に示したように使ってみてほしい

2024-01-25 07:31 UTC, alter334 commented
これ再起動時に何もしてないな(反映させます)

2024-01-25 14:27 UTC, Pugma requested changes
確認しました
もう少しだけお願いします！:pray:

2024-01-25 14:27 UTC, Pugma commented on server/traqmessage/collect.go
> -	lastCheckpoint := time.Now()
これ残しておかないと、DBに最終の時刻が載っていない場合に参照する時刻がない状態となってエラー吐いて終了するので、初回のDB記録ができない状態で無限ループしそうな気がします

2024-01-25 15:24 UTC, Pugma requested changes
あとこれも確認よろしく！

2024-01-25 15:24 UTC, Pugma commented on server/traqmessage/collect.go
>  			}
なんかbreakが2つあるので先の方は消して良さそう

2024-01-25 15:24 UTC, Pugma commented on server/traqmessage/collect.go
> +			}
```suggestion
			// ページ0の時なら検索対象最新メッセージが真に最新メッセージ
			if page == 0 {
				tmplastCheckpoint = (*messages)[0].CreatedAt
			}
```
とすれば一時変数不要そうね

2024-01-27 00:43 UTC, alter334 commented
他何か改善点ありましたっけ
あったようななかったような

2024-01-27 01:39 UTC, Pugma commented
一旦mainブランチの変更点を取り込んでほしいかも

2024-01-27 11:09 UTC, Pugma commented on server/traqmessage/collect.go
> +		}
ここの`break`消してほしいです
そうしないと、一度DBエラーが出たら3分おきにポーリングするためのfor文から抜けてしまって完全に停止してしまいます

2024-01-29 04:29 UTC, alter334 commented on server/traqmessage/collect.go
> +		}
修正しました

2024-01-29 04:37 UTC, Pugma approved these changes
問題なさそうです！
改善ありがとうございました！！！

2024-01-29 04:37 UTC, merged